### ISSUE TITLE
Different instances of `PushNotifications` with different configs.

### ISSUE THREAD

**Issue by vedi** [appfeel/node-pushnotifications#10]
In my backend I need to use different setting in pushes in different conditions. Unfortunately shared `settings` (https://github.com/appfeel/node-pushnotifications/blob/master/lib/push-notifications.js#L8) breaks the logic.

I've prepared PR (https://github.com/appfeel/node-pushnotifications/pull/11), which fixes this. Please, merge, or apply other fix, and publish fixed version.

**Comment by appfeel** [comment]
Thanks, merged
