### ISSUE TITLE
Fix documentation: locArgs is bodyLocArgs

### ISSUE THREAD

**Issue by thebitcoin4me** [appfeel/node-pushnotifications#102]
Documentation says the localized body arguments are "locArgs" but for APN they are "bodyLocArgs"

      alert: data.alert || {
                title: data.title,
                body: data.body,
                'title-loc-key': data.titleLocKey,
                'title-loc-args': data.titleLocArgs,
                'loc-key': data.locKey,
                'loc-args': data.bodyLocArgs,
                'launch-image': data.launchImage,
                action: data.action
            },

**Comment by alex-friedl** [comment]
Closed as outdated
