### ISSUE TITLE
Does it supports push kit?

### ISSUE THREAD

**Issue by lboquan** [appfeel/node-pushnotifications#109]
It works well with apns and gcm or fcm. Recently, I would like to move my project to PushKit without any success. Does this module supports PushKit or not?

**Comment by alex-friedl** [comment]
Hello @lboquan,
if node-apn supports it, you should be able to get it working as well with this lib.
Have you tried the advice given in https://github.com/node-apn/node-apn/issues/464 ?

**Comment by lboquan** [comment]
I tried this by adding a suffix ".voip" in my topic but got a 'TopicDisallowed' error.

**Comment by alex-friedl** [comment]
Hello @lboquan 
were you able to fix your issue or are you still experiencing problems?
Looks like a configuration issue, but if you provide some more details, I would be happy to help you

**Comment by lboquan** [comment]
I finally found it's my problem. It's because the way I make my .pem files from cert and key is not correct.

**Comment by alex-friedl** [comment]
Glad it worked out :)
