### ISSUE TITLE
APN Configuration without p8 key

### ISSUE THREAD

**Issue by trigun539** [appfeel/node-pushnotifications#112]
Followed the documentation, however I'm unable to get a p8 file from the apple developer site. 
Only thing I have been able to get for push notifications is a certificate:

The documentation show the following:
![image](https://user-images.githubusercontent.com/508205/60393351-f4fc3800-9ae1-11e9-9c2c-c53636b07a6d.png)

But I can't get the p8 file:
![image](https://user-images.githubusercontent.com/508205/60393375-7a7fe800-9ae2-11e9-9bfb-b70b31c7c74d.png)

The only option I can see, is a certificate for a push notification service which I got:
![image](https://user-images.githubusercontent.com/508205/60393372-69cf7200-9ae2-11e9-95de-00c94c37debd.png)

Does anyone have some example code on how to use this certificate in the configuration?

**Comment by sharma0611** [comment]
You can setup a certificate via these instructions: https://github.com/node-apn/node-apn/wiki/Preparing-Certificates

Or you can setup the key via the instructions here: https://developer.clevertap.com/docs/how-to-create-an-ios-apns-auth-key

**Comment by sharma0611** [comment]
You can setup a certificate via these instructions: https://github.com/node-apn/node-apn/wiki/Preparing-Certificates

Or you can setup the key via the instructions here: https://developer.clevertap.com/docs/how-to-create-an-ios-apns-auth-key

**Comment by alex-friedl** [comment]
Thank you for clarifying @sharma0611! :)

**Comment by trigun539** [comment]
Just tried to create the .p12 cert as the instructions say but keychain doesn't allow export to .p12 from first link. Now, trying to follow the token way but not sure how to configure this library to work with tokens.

![image](https://user-images.githubusercontent.com/508205/60762477-18b60580-a02f-11e9-826e-a899d7b668b5.png)

The second link talks about instructions to old developer.apple.com site and those steps can't be done on new site.
