### ISSUE TITLE
Can I please have ownership of "react-native-google-admob" package name?

### ISSUE THREAD

**Issue by thecodrr** [appfeel/node-pushnotifications#116]
_Sending this here as you didn't reply on [#1](https://github.com/appfeel/react-native-google-admob/issues/1)_
Hi,

Recently, due to unknown reasons, the maintainer of react-native-admob stopped maintaining the package and we were left in the dark. As I am an active contributor in everything React Native, I decided to fork the project and start maintaining my own package called react-native-google-admob. I forgot to check if a package with such a name already existed on npm and finding out that it does I decided to contact you.

Can you please either unpublish the package or transfer it to me as it seems uninitiated (last commit 3 years ago)?

Thank you, I hope you will consider.

PS. My npm username is theweavrs if you do decide to transfer ownership.

**Comment by alex-friedl** [comment]
wrong repository?

**Comment by thecodrr** [comment]
@alex-friedl I made an issue on your other (the react-native-google-admob) repo too, but you didn't reply.

**Comment by alex-friedl** [comment]
@thecodrr I don't own a repo of that name?

**Comment by thecodrr** [comment]
This repo: https://github.com/appfeel/react-native-google-admob/

It's under the same username. Not yours but I had still the same.

**Comment by alex-friedl** [comment]
@miqmago is the owner of everything under /appfeel :)

**Comment by thecodrr** [comment]
Any way to contact him?
