### ISSUE TITLE
Support iOS 13 with Push Type

### ISSUE THREAD

**Issue by tangkhaiphuong** [appfeel/node-pushnotifications#118]
Please support IOS 13 with push type.

**Comment by alex-friedl** [comment]
Could you please provide documentation, regarding the changes that are necessary? 
What is not working on iOS 13 with the current setup?

**Comment by novvai** [comment]
iOS 13 have introduced new header **apns-push-type** that is required for watchOS 6 and its recommended for iOS, macOS, etc ([documentation](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns?language=objc)). Currently the latest version of **node-apn** is supporting pushType property that is used to send this header ([documentation](https://github.com/node-apn/node-apn/blob/master/doc/notification.markdown#notificationpushtype))

**Comment by alex-friedl** [comment]
Thank you for the information :)
I will try to implement as soon as possible

**Comment by alex-friedl** [comment]
Hey @novvai @tangkhaiphuong : Could you test my branch `ios-push-type` and see if it works for you as expected? Thank you! :)

**Comment by novvai** [comment]
I've tried it, it looks all good to me. Thanks for the fast response.
