### ISSUE TITLE
Why does it keep living when all notifications sent?

### ISSUE THREAD

**Issue by presidenten** [appfeel/node-pushnotifications#12]
When I send some notifications the push service seem to live on. 
And when I call it again async a few times, it seems like I end up with more instances.

Am I supposed to feed the living service new device_tokens and messages in some way?

**Comment by rpopovici** [comment]
same issue here

**Comment by rpopovici** [comment]
apparently you have to shutdown the apns connection after you finished sending by calling APNConnection.shutdown()

**Comment by wordempire** [comment]
@rpopovici Where would I need to call this?

**Comment by appfeel** [comment]
Implemented in last version
