### ISSUE TITLE
when app is killed by user, notification alert & badge both came. while clicking on notification badge icon "notification" event in mobile is not getting called, can u help me out with this ???

### ISSUE THREAD

**Issue by GawandeC** [appfeel/node-pushnotifications#121]
ios notification payload is::
let note={ alert: notification.message,
            sound: "default",
           // contentAvailable: true, 
            title: notification.title,
            badge:1, 
            body : { 
              notId: this.createGuid(),
              extra_data:notification.extra_data
            },
			 custom : { 
              notId: this.createGuid(),
              extra_data:notification.extra_data
            },
            expiry: Math.floor(Date.now() / 1000) + 28 * 86400,
            priority: 'high', 
            topic: "com.kanverse.jadeglobal.mqa"
           };

    return note;

**Comment by alex-friedl** [comment]
Sorry, this is rather unspecific and confusing. I suppose it is an issue with your app, rather than with the library?

**Comment by miqmago** [comment]
I think so @alex-friedl 
Please @GawandeC reopen with more information if you think it's relevant to this library.
