### ISSUE TITLE
ExperimentalWarning: The http2 module is an experimental API

### ISSUE THREAD

**Issue by derwaldgeist** [appfeel/node-pushnotifications#122]
I want to use this package inside a Meteor 1.8 app, which is based on Node 8.11.4 (included in Meteor).

If I run my app, I get the following warning on the console:

`ExperimentalWarning: The http2 module is an experimental API.`

Is there a version of this package which is compatible to Node 8? Or can this error be ignored / suppressed?

**Comment by alex-friedl** [comment]
@derwaldgeist the module itself is compatible with node 8. The warning will be part of node-apn, which uses the http2 module I assume. I think it can be safely ignored but it could also make sense to upgrade to a higher node version if possible (maybe a more recent meteor version includes it?)

**Comment by derwaldgeist** [comment]
@alex-friedl Thanks for the info. So far, all is working well. Yes, there's a newer Meteor version with a more recent Node version, but upgrading is currently not an option for me.
