### ISSUE TITLE
Production Key in APN

### ISSUE THREAD

**Issue by StNebel** [appfeel/node-pushnotifications#134]
When I deploy the app with ad-hoc. 
Do I need true or false in the production parameter?

See https://github.com/node-apn/node-apn/blob/master/doc/provider.markdown

thx4help

**Comment by alex-friedl** [comment]
It depends on if your token is for the sandbox or production environment of APNS.

Apple docs: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns/
