### ISSUE TITLE
Push notifications in Android only work when PhoneGap app is in foreground

### ISSUE THREAD

**Issue by pmkruyen** [appfeel/node-pushnotifications#135]
Hi all,

Thanks for this amazing module.

For iOS devices everything works as expected, but for Android push notifications are only received when the app is in foreground. 

I just asked a question about this behavior on [StackOverflow](https://stackoverflow.com/questions/63148989/push-notifications-in-android-only-work-when-phonegap-app-is-in-foreground). But then I realized it might be better to pose the question here.

Any help is appreciated.

Thanks,
Peter

PS. When I am right about this, I would like to suggest to add a small comment to the set-up file that explains that the `gcm id` refers to the Firebase server key.

**Comment by alex-friedl** [comment]
Please re-open if there are any further questions
