### ISSUE TITLE
Support legacy binary protocol to HTTP/2-based Apple Push Notification

### ISSUE THREAD

**Issue by kushalhyperlink** [appfeel/node-pushnotifications#139]
Hello Team,

As per the recent announcement from apple 

If you still send push notifications with the legacy binary protocol, it's time to update to the HTTP/2-based Apple Push Notification service (APNs) provider API. You'll be able to take advantage of great features, such as authentication with a JSON Web Token, improved error messaging, and pre-notification feedback.

To give you additional time to prepare, the deadline to upgrade to the APNs provider API has been extended to March 31, 2021. We recommend upgrading as soon as possible, as APNs will no longer support the legacy binary protocol after this date.

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns

How to support HTTP/2-based Apple Push Notification using node-pushnotifications

Thanks in advance.

**Comment by vitalyster** [comment]
Make sure you are using the latest node-pushnotifications package, it is already utilized HTTP/2 API

**Comment by kushalhyperlink** [comment]
Thank you for the prompt update, I believe v1.4.1 utilized HTTP/2 API

**Comment by alex-friedl** [comment]
@kushalhyperlink That's right, we are using https://www.npmjs.com/package/@parse/node-apn for APNS, which uses the HTTP/2 API.
