### ISSUE TITLE
Errors with example data

### ISSUE THREAD

**Issue by nickisobrien** [appfeel/node-pushnotifications#145]
It seems like these would be better provided as ``` undefined ```. Using ``` '' ``` throws errors. I guess they're supposed to be JSON arrays as strings and an empty string causes errors.

```
    locArgs: '', // gcm, apn
...
    titleLocArgs: '', // gcm, apn
```

**Comment by alex-friedl** [comment]
@nickisobrien Thanks for the hint! Fixed in #146
