### ISSUE TITLE
Extract device type detection method

### ISSUE THREAD

**Issue by jkblume** [appfeel/node-pushnotifications#148]
Hi there, i am interested in logging / saving the detected device type in my application. Do you think you welcome a PR, where I extract your device detection method to an own method, that can be used outside of the lib to track a device type for a given device token?

**Comment by alex-friedl** [comment]
@jkblume Sure, that could be done. Just make sure that the additional export does not break the existing API. 
Alternatively you could always just take that piece of code and integrate it into a custom lib on your end :)

**Comment by jkblume** [comment]
Yeah for now i'm going your proposed way, but want to make sure that my implementation matches the one in your lib :) Will give it a try and open a PR if i come to a good solution.

**Comment by jkblume** [comment]
Opened a PR here: https://github.com/appfeel/node-pushnotifications/pull/149 . Happy to hear your feedback :)

**Comment by alex-friedl** [comment]
Merged #149 and released in [v1.7.0](https://github.com/appfeel/node-pushnotifications/releases/tag/1.7.0)
