### ISSUE TITLE
How do I ignore adm (Amazon)

### ISSUE THREAD

**Issue by voidstarfire** [appfeel/node-pushnotifications#15]
I removed the adm configuration and now it errors.
When I put in the default one it still errors.

How do I remove it?

**Comment by appfeel** [comment]
Maybe you have some tokens not matching any other criteria. The array of tokens is the following one:

```js
    if (pushId[i].substring(0, 4) === 'http') {
      regIdsMPNS.push(pushId);
    } else if (pushId[i].length > 64) {
      regIdsGCM.push(pushId[i]);
    } else if (pushId[i].length === 64) {
      regIdsAPN.push(pushId[i]);
    } else if (true) { // need to find condition for amazon token
      regIdsADM.push(pushId[i]);
    }
```

Your option is to remove all ADM tokens before sending notifications. If you pass ADM tokens, it is expected to send ADM notifications. Please, could you confirm this? Thanks
