### ISSUE TITLE
sending images with app

### ISSUE THREAD

**Issue by arnaudambro** [appfeel/node-pushnotifications#156]
Hi there,
Great lib, thanks !
However, I have hard time sending an image in an iOS notification : is it the launchImage field ? filled with an url ? any other field required ?
I couldn't find the proper doc on the web yet...

thanks for your help !

**Comment by vitalyster** [comment]
You need to create Service Extension in your iOS app to download URLs from your notifications and display them with custom notification layout. See https://developer.apple.com/documentation/usernotifications/modifying_content_in_newly_delivered_notifications?language=objc

**Comment by alex-friedl** [comment]
@arnaudambro Does it work for you now, following the advice from @vitalyster ?

**Comment by arnaudambro** [comment]
I dob't know, I didn't try yet, it's not an easy work to do !

**Comment by alex-friedl** [comment]
Will close this for now. Please re-open if you re-encounter the issue and think it's related to an issue with the library
