### ISSUE TITLE
sendAPN handling of received token in success case inconsistent with other cases and providers

### ISSUE THREAD

**Issue by henry-tm** [appfeel/node-pushnotifications#159]
When mapping through received token for sent notifications in sendAPN module the logic assumes that the received tokens are strings (https://github.com/appfeel/node-pushnotifications/blob/master/src/sendAPN.js [line 108ff]):
```javascript
(response.sent || []).forEach((token) => {
  resumed.success += 1;
  resumed.message.push({
    regId: token,
    error: null,
  });
});
```

In fact, looking at the implemenation of the success case logic in the `node-apn` package, the `device` is wrapped in an object literal (https://github.com/node-apn/node-apn/blob/master/lib/client.js [line 74ff]):
```javascript
...
stream.on("end", () => {
  if (status === "200") {
    resolve({ device });
  } else if ...
```

To be conistent with the other cases handled in the sendAPN module, it would be great to pick the `device` prop and set as `regId` instead of returning the property wrapped in an object literal.

**Comment by alex-friedl** [comment]
@henry-tm Thank you for reporting this! Should be fixed in [v1.6.3](https://github.com/appfeel/node-pushnotifications/releases/tag/1.6.3)
