### ISSUE TITLE
Support for data-only messages on Android

### ISSUE THREAD

**Issue by derwaldgeist** [appfeel/node-pushnotifications#166]
We're building a Unity application using a package that supports only "data-only"-messages on Android. Is there a way to tell `node-pushnotifications` to keep the `notifications` key out if the notification is being sent via FCM?

**Comment by vitalyster** [comment]
Magical `phonegap` option will do what you need

**Comment by derwaldgeist** [comment]
Oh, thanks, I had seen this option, but thought it was for `phonegap` / Cordova only :-) Will try it out!

**Comment by derwaldgeist** [comment]
Yeay, it worked! Thank you so much for your super-fast response!
