### ISSUE TITLE
Cannot create PushNotification instance

### ISSUE THREAD

**Issue by aotol** [appfeel/node-pushnotifications#168]
I was following the instruction on page:
https://www.npmjs.com/package/node-pushnotifications

It was all good till recently, NodeJS start complaining during runtime:
TypeError: PushNotifications is not a constructor

At line:
const push = new PushNotifications(settings);

**Comment by alex-friedl** [comment]
@aotol Thank you for reporting this. Did it work with v1.7.1 but stopped working with v1.7.2 ?

**Comment by alex-friedl** [comment]
Should be fixed in v1.7.3

**Comment by mrevanzak** [comment]
hey i got this too in 3.1.1
