### ISSUE TITLE
Breaking changes in dependecy node apn

### ISSUE THREAD

**Issue by Ryanthegiantlion** [appfeel/node-pushnotifications#17]
When trying to send an apple push there is the following error:

```
TypeError: apn.Connection is not a constructor
```

This seems to be related to breaking changes in the node-apn package (apn.Connection has been renamed to apn.Provider):

https://github.com/argon/node-apn/blob/develop/doc/whats-new.markdown

The node-apn dependency should be pinned to 1.* until the library accomodates for the changes in v2 of the node apn package.

**Comment by vedi** [comment]
Experiencing the same issue. I think it's better to constrain all dependency version. Sooner or later we'll got issues with other libraries as well.

**Comment by appfeel** [comment]
Solved in https://github.com/appfeel/node-pushnotifications/pull/11
