### ISSUE TITLE
Update node-forge to fix security vulnerabilities

### ISSUE THREAD

**Issue by davidschuette** [appfeel/node-pushnotifications#172]
I use the latest version of node-pushnotifications in a project of mine.

I recently found out that the currently used version of `node-forge` has a number of security issues. Is there any possibility of an upgrade to fix these vulnerablities?

All the issues have been patched in version >= 1.3.0.

**Comment by alex-friedl** [comment]
I opened an issue with @parse/node-apn and asked them to look into updating the version they are using: https://github.com/parse-community/node-apn/issues/103

**Comment by davidschuette** [comment]
Thank you.

**Comment by tommyvigneaultdev** [comment]
Seems @parse/node-apn released version 5.1.3 with the fix. All that's left to do is to upgrade the dependency here.
