### ISSUE TITLE
Not all users receive push notifications

### ISSUE THREAD

**Issue by derwaldgeist** [appfeel/node-pushnotifications#189]
Hey appfeel,

we're using version 1.5.0 of this package in production for quite some time now, and noticed that not all users receive notifications if we send out a lot of them at the same time (typically around 3.000). What may be the reason for this? Should we better send these notifications in chunks? From the documentation, I had assumed that the package already does this.

As a side-question: I saw that package has been update to a new major version. Are there any breaking changes / an upgrade guide, or should it "just work"?

Thanks for maintaining this!

**Comment by georgiosd** [comment]
@derwaldgeist did you find the cause of this?

**Comment by derwaldgeist** [comment]
Yes, it was actually a bug in my own implementation, not related to node-pushnotifications. I had implemented a logic to control which users receive push notifications or not. And in one database update, I accidentally disabled the push notifications for all existing users.
