### ISSUE TITLE
node-gcm library is End of Life on June 21st, 2024

### ISSUE THREAD

**Issue by giantslogik** [appfeel/node-pushnotifications#208]
node-pushnotifications uses https://github.com/ToothlessGear/node-gcm which is EOL. 
`This package will stop working on June 21st, 2024, as it depends on the [Legacy FCM API](https://firebase.google.com/docs/cloud-messaging/migrate-v1). We urge you to migrate to another library that supports the FCM HTTP v1 API before the June 20th deadline`

Is there a migration path forward?

More information on the firebase API deprecation here: https://firebase.google.com/support/faq#fcm-23-deprecation

**Comment by giantslogik** [comment]
This PR exists. Are there plans to merge it in / test, and continue to maintain this library ?

https://github.com/appfeel/node-pushnotifications/pull/207

**Comment by alex-friedl** [comment]
We would love to continue maintenance on this library and merge the open PR for FCM support, if you can confirm that it works properly. Personally I don't have a working setup anymore for testing Android push notifications

**Comment by giantslogik** [comment]
Just noting that this EOL also impacts the web-push library used by node-pushnotifications

https://github.com/web-push-libs/web-push/issues/893

**Comment by alex-friedl** [comment]
I released #207 with some minor linter fixes now.

Let's see how it goes with that version in the wild and deal with eventual bugfixes once people adapt the new version.

I will also look into removing the legacy `isAlwaysUseFCM` parameter if I find the time (PRs would of course be welcome)
