### ISSUE TITLE
How to send iOS 10 Rich Notifications?

### ISSUE THREAD

**Issue by ArifADS** [appfeel/node-pushnotifications#21]
Basically I want to know how to send the `"mutable-content" = 1 ` in the APN, I tried sending it with custom, but no luck, there is no actual way to know what is exactly sending to Apple, right?

**Comment by ArifADS** [comment]
I added at the end of the message object in sendAPN.js
`mutableContent: data.mutableContent || 0` and it works now, and the data needed I send it in custom, I don't know if it is the right way or you meant to do it differently, but it works.

**Comment by miqmago** [comment]
Thanks, it should be working now.
