### ISSUE TITLE
Support for FCM

### ISSUE THREAD

**Issue by MichaelHuy** [appfeel/node-pushnotifications#22]
can we update the lib to support FCM

**Comment by appfeel** [comment]
Any pull request for this will be really appreciated.

**Comment by alex-friedl** [comment]
@MichaelHuy: What features for FCM are you missing? The current implementation works for me with a FCM API key ...

**Comment by appfeel** [comment]
I have no experience in FCM, @alex-friedl  could you describe how you use it? An example or similar. If it works without touching the source code and @MichaelHuy can verify it, I can update the readme  :)

**Comment by alex-friedl** [comment]
I use it exactly how the README describes GCM usage. Get an API Key from the firebase console (instead of the GCM console) and use it in the settings object

```
gcm: {
      id: '<yourKey>'
}
```

**Comment by appfeel** [comment]
@MichaelHuy does it work for you? Please feel free to reopen the issue otherwise

**Comment by sagarpatel9697** [comment]
Hi @alex-friedl, as you mentioned above. I have to replace FCM API key to GCM id for using FCM with package. is that enough or any other changes also require ?
I want to use this package for Android and ios device push notification and package documentation dosen't have detail about usage of FCM.

**Comment by alex-friedl** [comment]
Hi @sagarpatel9697 
that should be enough. The most recent version of node-gcm, which is already used as a dependency, handles the witch from GCM to FCM for us.
