### ISSUE TITLE
Error NotRegistered

### ISSUE THREAD

**Issue by harshalyeole-tudip** [appfeel/node-pushnotifications#24]
Hi, I'm trying to use it but it gives error and say :
 messageId: undefined,
    regId: undefined,
    error: 
     Error: NotRegistered
         at /home/lt-101/sebas/api/node_modules/node-pushnotifications/lib/sendGCM.js:37:50
         at Array.map (native)
         at /home/lt-101/sebas/api/node_modules/node-pushnotifications/lib/sendGCM.js:33:47
         at /home/lt-101/sebas/api/node_modules/node-gcm/lib/sender.js:47:24
         at /home/lt-101/sebas/api/node_modules/node-gcm/lib/sender.js:211:14
         at _combinedTickCallback (internal/process/next_tick.js:67:7)
         at process._tickCallback (internal/process/next_tick.js:98:9) }

**Comment by appfeel** [comment]
This is a result report.
The token you are sending push notifications to is not registered in google.
This means that you are trying to send a notification to a device that has called unregister receiving push notifications (or maybe has uninstalled your app).
