### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by charithvalluru** [appfeel/node-pushnotifications#3]
I am getting this error:
"Cannot read property 'sendPush' of undefined".

Request you to please help me out in this.

**Comment by CookieCookson** [comment]
I'm getting the same error here!

**Comment by CookieCookson** [comment]
Fixed it by doing:

```
var settings = {...}
var pushnotifications = require('node-pushnotifications');
var push = new pushnotifications(settings);
push.send(...);
```

**Comment by miqmago** [comment]
Thanks @CookieCookson , does this work for you @charithvalluru ?
Reopen issue with your code in contrary case.

**Comment by miqmago** [comment]
Please note also that there was a bug that has been solved https://github.com/appfeel/node-pushnotifications/pull/2 so you should update to 0.1.5:

```bash
$ npm i node-pushnotifications
$ npm i node-pushnotifications@0.1.5       # if you are using npm with target versions
```
