### ISSUE TITLE
priority param different for Google and IOS

### ISSUE THREAD

**Issue by reijosirila** [appfeel/node-pushnotifications#36]
GCM expects string, but APN expects integer. 
How to define prioroties for both ?

**Comment by alex-friedl** [comment]
Good point @reijosirila.

I looked into the current documentations and it looks like both GCM and APN basically have two different priorities. GCM calls them _normal_ and _high_ whereas APN uses _5_ and _10_.

@appfeel: We should probably have the API accept _high_ and _normal_ as values and translate this for APN to the respective integer values? What do you think?

**Comment by appfeel** [comment]
@alex-friedl yes, that would be the solution.

@reijosirila @alex-friedl are you available to implement? Otherwise I'll try to dedicate time during next 2 weeks.

**Comment by alex-friedl** [comment]
@appfeel: I could try to implement it this weekend.

**Comment by alex-friedl** [comment]
@appfeel, @reijosirila https://github.com/appfeel/node-pushnotifications/pull/39 
Hope this is what you are looking for

**Comment by reijosirila** [comment]
Looks good. Thanks 👍

**Comment by appfeel** [comment]
https://github.com/appfeel/node-pushnotifications/pull/39
