### ISSUE TITLE
Response is not clear

### ISSUE THREAD

**Issue by nesimtunc** [appfeel/node-pushnotifications#38]
Hi, 
The response output after the push sent is not clear especially for failure. Please see this output.

`[{"method":"apn","success":1,"failure":1,"message":[{"regId":{"device":"token1"},"error":null},{"regId":"token2","error":{}}]}]`

**Comment by alex-friedl** [comment]
@appfeel: Possible duplicate of https://github.com/appfeel/node-pushnotifications/issues/34?

**Comment by alex-friedl** [comment]
Closed as duplicate of #34. 

@nesimtunc Please see my last comment in the referenced issue. Maybe you could provide more detailed logs in order for us to understand better why the error response is empty?
