### ISSUE TITLE
please create example for working with react-native

### ISSUE THREAD

**Issue by hemedani** [appfeel/node-pushnotifications#41]
please provide an example folder for more clear how to use document and also create a full documented example for react-native in IOS and Android
tanx

**Comment by rickardinho** [comment]
yes please,  i'm struggling with what to include for keyID, as there's nothing in the apple developer portal by that name, even after creating the aps certificate and key.

**Comment by kylealwyn** [comment]
This is a pretty solid article integrating react native with this lib: https://shift.infinite.red/react-native-node-js-and-push-notifications-e851b279a0cd

**Comment by rickardinho** [comment]
Thanks this is helpful, but it doesn't answer my question on the keyID.  From the Apple developer portal I got a .p12 key and not a.p8. there is not mention of keyID on the developer portal

**Comment by alex-friedl** [comment]
Hello @rickardinho,
you can find your keyID in the Apple developer portal, if you click on your Auth. Token entry in your keys list https://developer.apple.com/account/ios/authkey/ 
The detail page for your Auth key will include the key id

**Comment by alex-friedl** [comment]
Hello @hemedani.
 I wrote a little sample setup using this library and a React Native app. 
You can find it at https://github.com/alex-friedl/crossplatform-push-notifications-example

Currently the app itself only works with Firebase, the server part will work with everything.

Hope this helps :)

**Comment by alex-friedl** [comment]
Closed with link to https://github.com/alex-friedl/crossplatform-push-notifications-example
