### ISSUE TITLE
How to keep connection open?

### ISSUE THREAD

**Issue by EGreg** [appfeel/node-pushnotifications#47]
Looking at the code, you create a new connection every single time.

Is there a way to re-use connections? I want to submit a pull request with the option to save the connection inside the object!

See this: http://stackoverflow.com/questions/20763514/sending-5000-push-notifications-at-same-time-keep-the-connection-to-apple-open

**Comment by EGreg** [comment]
From node-apn docs:

"You should only create one Provider per-process for each certificate/key pair you have. You do not need to create a new Provider for each notification. If you are only sending notifications to one app then there is no need for more than one Provider.

If you are constantly creating Provider instances in your app, make sure to call Provider.shutdown() when you are done with each provider to release its resources and memory."

**Comment by alex-friedl** [comment]
Fixed this in a5df7da. One provider is re-used across requests now.
