### ISSUE TITLE
[Bug] GCM tokens recognition problem

### ISSUE THREAD

**Issue by olegmdev** [appfeel/node-pushnotifications#57]
GCM push tokens may include both `amzn` and `adm` substrings (just got one). So in fact you will send GCM token to ADM and it'll be failed.

https://github.com/appfeel/node-pushnotifications/blob/master/src/push-notifications.js#L89

**Comment by alex-friedl** [comment]
Duplicate of #53 ?

**Comment by olegmdev** [comment]
@alex-friedl right, closing this one
