### ISSUE TITLE
tag does not works when opts.phonegap is true

### ISSUE THREAD

**Issue by daniel-mf** [appfeel/node-pushnotifications#60]
When option `phonegap` is true,`tag` option stops working, then the notifications are always replaced.

Could someone help?

**Comment by alex-friedl** [comment]
@daniel-mf Thanks for the bug report. I implemented the `phonegap`option and will look into it this weekend and hopefully come up with a PR.

**Comment by daniel-mf** [comment]
@alex-friedl Thank you!

**Comment by alex-friedl** [comment]
Hi @daniel-mf,

I was able to reproduce the behaviour and researched your issue a bit.

It seems that the `tag` field needs to be part of the `notification`payload. 

The `phonegap=true`option will send a so called _data message_ without a `notification`payload, as [recommended here](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#notification-vs-data-payloads).

So either the behaviour to read tags from the data payload needs to be implemented by Google or the authors of the [PhoneGap Push Plugin](https://github.com/phonegap/phonegap-plugin-push) will provide some sort of workaround for this issue. But having tags in data notification is not something we can implement in this module.

Sorry!

**Comment by daniel-mf** [comment]
@alex-friedl I appreciate your help, thanks!
