### ISSUE TITLE
nsp fails due to https://nodesecurity.io/advisories/534

### ISSUE THREAD

**Issue by BDav24** [appfeel/node-pushnotifications#63]
The problem comes from `debug` version of `node-gcm` and `node-apn`.

> Note: There is a PR for `node-apn`: https://github.com/node-apn/node-apn/pull/595/files

**Comment by BDav24** [comment]
Issue on `node-gcm`: https://github.com/ToothlessGear/node-gcm/issues/309

**Comment by alex-friedl** [comment]
Fixed in https://github.com/appfeel/node-pushnotifications/commit/5d856b93601f6c8a26d52ce6498ed4ba3cb9b601.
Will be part of the next release
