### ISSUE TITLE
Wrong callback behavior.

### ISSUE THREAD

**Issue by r0b1n** [appfeel/node-pushnotifications#7]
For iOS:
This always goes to first parameter which means `error`:
https://github.com/appfeel/node-pushnotifications/blob/master/lib/push-notifications.js#L118-L123
Even if it is completed.

Also documentation is wrong, `send` callback should contain `error` and `result` parameters.

**Comment by miqmago** [comment]
I see the problem. I'm just completly refactoring to provide better error handling and api.
I will provide feedback soon.

**Comment by vedi** [comment]
I used such workaround to solve this: 
https://github.com/vedi/node-pushnotifications/commit/1dae83d2ded453469e9ddc23d5fff2ae6917c655

**Comment by appfeel** [comment]
Fixed in https://github.com/appfeel/node-pushnotifications/pull/11, thanks
