### ISSUE TITLE
GCM does not send to Android 7.0 and above

### ISSUE THREAD

**Issue by Jp3rd** [appfeel/node-pushnotifications#71]
I did the exact same thing for Android 6.0 and it works perfectly.
However, when I tried using Postman it gets the notification on all devices. Is there something I need to do on GCM or FCM for Android 7.0 and above to work?

**Comment by irjinn** [comment]
@Jp3rd looks like it's not an issue with node-pushnotifications package. 
By the way, are you referring to one of those devices: Huawei, Xiaomi, Asus?
Some modern android devices are pretty restrictive, may be this [page](https://docs.telerik.com/platform/knowledge-base/troubleshooting/troubleshooting-cannot-receive-push-notifications-on-android-when-the-app-is-closed) will help you to resolve the issue.

**Comment by alex-friedl** [comment]
Not an issue with the lib. Would be glad to help, but more information is needed.
Closing this for now.
