### ISSUE TITLE
APN contentAvailable (1) isn't compatible with GCM contentAvailable (true) 

### ISSUE THREAD

**Issue by calvinckho** [appfeel/node-pushnotifications#72]
In the JSON file, property contentAvailable for GCM and APN conflicts with each other. If you set contentAvailable to true, it works okay for GCM (which requires true) but does not work for APN (which requires 1).

**Comment by alex-friedl** [comment]
Fixed in https://github.com/appfeel/node-pushnotifications/pull/73

**Comment by calvinckho** [comment]
Great! Glad to know this. Maybe you can clarify it in the documentation? It is not very clear whether we should use 'true' or 1 for contentAvailable. Thanks!

    contentAvailable: true, // gcm for android
    delayWhileIdle: true, // gcm for android
    restrictedPackageName: '', // gcm for android
    ...
    action: '', // apn and gcm for ios
    category: '', // apn and gcm for ios
    contentAvailable: '', // apn and gcm for ios

**Comment by alex-friedl** [comment]
Hi @calvinckho .
What do you think about https://github.com/appfeel/node-pushnotifications/pull/80/? Is it sufficiently clear in this form?

**Comment by alex-friedl** [comment]
Updated README in https://github.com/appfeel/node-pushnotifications/commit/fa64a98fc00717f6adfad74975d219ffe29fdc3e
