### ISSUE TITLE
WNS sendRaw: Error: The payload parameter must be the notification payload string.

### ISSUE THREAD

**Issue by nelsona** [appfeel/node-pushnotifications#75]
When trying to send raw notifications using WNS the following error is returned:
`Error: The payload parameter must be the notification payload string.`

This is happening because in the sendWNS.js file the data being set across to WNS is using 
`Object.assign({}, _data)` (line 49)
before it is sent over, this is fine for all other windows notification type apart from raw which expects a string of data rather than an object.

**Comment by alex-friedl** [comment]
Hello @nelsona ,
I created https://github.com/appfeel/node-pushnotifications/pull/81 as a bugfix.
Unfortunately I can't test this feature for lack of Windows software and hardware.

Could you test the branch and give me feedback if it works as expected?

Regards
Alex
