### ISSUE TITLE
Wrong message on iOS Push Notification

### ISSUE THREAD

**Issue by igordeoliveirasa** [appfeel/node-pushnotifications#8]
You are passing title instead of message, when iOS Token is detected. This way, whenever I send a notification like: {title:"My App's name", message:"Information message"}, the device receives a notification alert like:

title: My App's name
message: My App's name

**Comment by phoxoey** [comment]
I'm getting the same behavior.

**Comment by phoxoey** [comment]
After looking at the code I was able to fix the issue. On line: 123 in push-notifications.js change "messageAPN.alert = data.title;" to "messageAPN.alert = {title: data.title, body: data.message};". I also commented out line:124 and 125.

**Comment by appfeel** [comment]
Fixed in https://github.com/appfeel/node-pushnotifications/commit/5090a96dee49d7bfb9dddb91d5c8bef1d1adb25b
