### ISSUE TITLE
Use published version of depenedencies instead of GIT dependency

### ISSUE THREAD

**Issue by anandanand84** [appfeel/node-pushnotifications#84]
Using git dependency may not work if there is not git install.

https://github.com/appfeel/node-pushnotifications/blob/master/package.json#L54

**Comment by alex-friedl** [comment]
Hi @anandanand84,

I use this fork in order to support WNS connections via http proxy. Unfortunately my PR is not being merged because the repo seems to be abandoned.

See original PR discussion https://github.com/appfeel/node-pushnotifications/pull/50

Maybe we should publish my fork to npm?

**Comment by anandanand84** [comment]
In that case I would recommend you publish your fork with a different name and maintain it.

**Comment by miqmago** [comment]
@anandanand84 we are asking @tjanczuk again if there is the possibility to merge wns fork https://github.com/tjanczuk/wns/pull/28. Meanwhile, have you tried to install git on your machine to see if it works?

Also if you are planning to maintain wns we encourage you to publish your own version in npm.

**Comment by tjanczuk** [comment]
I merged https://github.com/tjanczuk/wns/pull/28 and published as wns@0.5.4 on NPM.

**Comment by alex-friedl** [comment]
Thank you @tjanczuk!
I published v1.1.3 which includes wns@0.5.4 :)
