### ISSUE TITLE
SyntaxError: Unexpected token function (sendWeb.js line 9)

### ISSUE THREAD

**Issue by ezecafre89** [appfeel/node-pushnotifications#91]
Hi there! First of all, thanks for the work done here.

I just came across an issue with the latest release. It breaks if the node version doesn't support async/await.

In my case:
`node version: 6.12.2`

Cheers!

**Comment by alex-friedl** [comment]
Hello @ezecafre89 ,
thanks for the bug report! Fixed the issue in v1.1.2
