### ISSUE TITLE
Mention that topic needs to be set to bundle identifier APN

### ISSUE THREAD

**Issue by minlite** [appfeel/node-pushnotifications#97]
Current documentation does not mention that `topic` needs to be set to the bundle identifier for APN to work. 

I was seeing `MissingTopic` error if I didn't provide a topic, and a `TopicDisallowed` if I put anything other than my bundle identifier in the topic. 

Only place where this is mentioned is in #67.

**Comment by alex-friedl** [comment]
Added documentation to README in 0192482bb5f1cc262f8b2011246df8afad2ba85c
